export { analyzeProject, analyzeProgram } from "./analyze";
// Every rule this package runs, as four strings each — what a generator needs to describe them.
// The documentation site's rule tables are built from this, so they cannot drift from the rules.
export { ruleCatalogue } from "./rules";
export type { RuleSummary } from "./rules";
// Every issue `AnalyzeResult` carries, nameable. Two were once missing, so a script written
// against `analyzeProject` — which the reference tells people to write — could type a variable holding a
// context issue but not one holding a duplicate decorator.
export type {
  AnalyzeResult,
  AriaValueIssue,
  AriaWithNoSubjectIssue,
  ArrowFieldIssue,
  AsyncRenderIssue,
  AttributeThatDoesNothingIssue,
  BrowserUrlIssue,
  ClassInsteadOfClassNameIssue,
  ClickWithNoKeyboardPathIssue,
  ClientOnlyRequestReadIssue,
  ClockReadWhileRenderingIssue,
  CachedReadOfAPlainFieldIssue,
  ContextConsumedAboveItsProviderIssue,
  ControlWithNoLabelIssue,
  ComputeTakesNoArgumentsIssue,
  ContextIssue,
  DecoratorThatAddsNothingIssue,
  DevGuardAsAnExpressionIssue,
  DomWriteIssue,
  DuplicateDecoratorIssue,
  DuplicateIdIssue,
  DuplicateKeyAmongSiblingsIssue,
  EmptyHeadingOrLinkIssue,
  Findings,
  HeadingSkipsALevelIssue,
  FragmentLinkToNowhereIssue,
  FreshObjectInHookPropsIssue,
  FreshValueFromAWatchSelectorIssue,
  FreshObjectInPropsIssue,
  FunctionUsedAsATagIssue,
  ObjectAmongTheChildrenIssue,
  PropsWrittenByTheReceiverIssue,
  LazyImportsThatCollideIssue,
  FunctionBuiltInTheMarkupIssue,
  HeadTagsCollideIssue,
  IntervalWithNoCleanupIssue,
  InteractiveInsideInteractiveIssue,
  LateRequestReadIssue,
  IndexAsKeyIssue,
  LinkWithoutADestinationIssue,
  ListenerAddedByHandIssue,
  MediaWithNoCaptionsIssue,
  NamedOnlyByAPlaceholderIssue,
  OneProviderPerComponentIssue,
  PersistOfALossyValueIssue,
  PositiveTabIndexIssue,
  AccessKeyIssue,
  AriaHiddenOnFocusableIssue,
  PresentationRoleOnFocusableIssue,
  AriaStateWithNoRoleIssue,
  AutocompleteThatFillsNothingIssue,
  MoreThanOneMainIssue,
  LabelThatNamesNothingIssue,
  AriaStateTheRoleDoesNotHaveIssue,
  AriaHiddenAroundSomethingFocusableIssue,
  TableWithNoHeadersIssue,
  LandmarksThatCannotBeToldApartIssue,
  ParentWithAForeignChildIssue,
  AriaThatContradictsTheTagIssue,
  RoleThatFightsTheTagIssue,
  LiveRegionThatContradictsItsRoleIssue,
  ReferenceToAnIdThatIsNotThereIssue,
  RoleMissingRequiredAriaIssue,
  RegionWithNoNameIssue,
  FalseOnABooleanAttributeIssue,
  MisspelledElementPropertyIssue,
  HalfBuiltKeyboardPathIssue,
  ElementHtmlRemovedIssue,
  OptionThatCannotChooseIssue,
  RoleTakesNoNameIssue,
  RowWithoutAKeyIssue,
  ServerEnvInSharedCodeIssue,
  StateMutatedInPlaceIssue,
  StateWrittenWhileRenderingIssue,
  TagNeedsItsParentIssue,
  UnguardedAsyncLifecycleIssue,
  UnkeyableMemoizedArgumentIssue,
  UnknownAriaAttributeIssue,
  UnknownRoleIssue,
  UnnamedFrameIssue,
  UnnamedImageIssue,
  LensPathThroughAGapIssue,
  UnexposedEnvReadIssue,
  RowReadsAPlainFieldIssue,
  UnserializableStateIssue,
  UnsplittableImportIssue,
  UnwatchedFieldIssue,
  WatchOfAPropThatIsNotThereIssue,
} from "./analyze";
// The composition graph the issues are computed from. A FORMAT rather than an API: it is versioned
// by `schema` and there is no second consumer yet, so nothing here is documented for one.
export type { ComponentGraph, GraphEdge, GraphNode, Where } from "./graph";
// Two readings of that graph, both computed from it alone with no second walk over the source:
// where the app splits and what each piece carries, and what changed between two graphs.
export { filesOf, splitOf } from "./split";
export type { Split, SplitPoint } from "./split";
export { diffGraphs, refuseToDiff } from "./diff";
export type { GraphDiff } from "./diff";
