/* Generated by @ramonda/css from ramonda.css.ts. Do not edit. */

import type { CssColor, CssDimension, CssLengthUnit, CssTimeUnit, Fixed, Token } from "@ramonda/css";
import type { CssProperties as Base, CssBlock, CssCondition, CssFontFaceDescriptors, CssGlobal, CssKeyframesShape, CssPropertyDescriptors, CssSpreadable, CssValue, Keyword, Narrowed, StyleValue } from "@ramonda/css/properties";

/** Every variable this project declares. Reach one by the path it was declared at. */
export const $ = Object.freeze({
  "color": Object.freeze({
    "accent": Object.freeze({
      "main": "var(--color-accent-main)" as Token<"color", Fixed<"#10b981">>,
      "quiet": "var(--color-accent-quiet)" as Token<"color", Fixed<"#00b37e">>,
    }),
    "surface": Object.freeze({
      "base": "var(--color-surface-base)" as Token<"color", Fixed<"#ffffff">>,
      "sunken": "var(--color-surface-sunken)" as Token<"color", Fixed<"#f3f4f6">>,
    }),
    "text": Object.freeze({
      "primary": "var(--color-text-primary)" as Token<"color", Fixed<"#111827">>,
      "muted": "var(--color-text-muted)" as Token<"color", Fixed<"#6b7280">>,
    }),
  }),
  "space": Object.freeze({
    "gutter": Object.freeze({
      "tight": "var(--space-gutter-tight)" as Token<"length", Fixed<"8px">>,
      "normal": "var(--space-gutter-normal)" as Token<"length", Fixed<"16px">>,
      "wide": "var(--space-gutter-wide)" as Token<"length", Fixed<"24px">>,
    }),
  }),
  "size": Object.freeze({
    "radius": Object.freeze({
      "small": "var(--size-radius-small)" as Token<"length", Fixed<"4px">>,
      "pill": "var(--size-radius-pill)" as Token<"length", Fixed<"999px">>,
    }),
  }),
  "motion": Object.freeze({
    "quick": "var(--motion-quick)" as Token<"time", Fixed<"120ms">>,
    "calm": "var(--motion-calm)" as Token<"time", Fixed<"400ms">>,
  }),
});

/** The 205 properties this project narrows, and what each takes. */
interface Narrowings {
  /**
   * `z-index` — only the 5 value(s) this project permits.
   */
  "z-index": 0 | 1 | 10 | 100 | 1000 | Token<"integer" | "number", 0 | 1 | 10 | 100 | 1000> | CssGlobal | `var(${string})`;
  /** `-moz-border-bottom-colors` — a colour, and this project's variables of that kind. */
  "-moz-border-bottom-colors": Narrowed<"none", CssColor | Token<"color">>;
  /** `-moz-border-left-colors` — a colour, and this project's variables of that kind. */
  "-moz-border-left-colors": Narrowed<"none", CssColor | Token<"color">>;
  /** `-moz-border-right-colors` — a colour, and this project's variables of that kind. */
  "-moz-border-right-colors": Narrowed<"none", CssColor | Token<"color">>;
  /** `-moz-border-top-colors` — a colour, and this project's variables of that kind. */
  "-moz-border-top-colors": Narrowed<"none", CssColor | Token<"color">>;
  /** `-ms-content-zoom-limit-max` — a percentage, and this project's variables of that kind. */
  "-ms-content-zoom-limit-max": Narrowed<never, CssDimension<"%"> | Token<"percentage">>;
  /** `-ms-content-zoom-limit-min` — a percentage, and this project's variables of that kind. */
  "-ms-content-zoom-limit-min": Narrowed<never, CssDimension<"%"> | Token<"percentage">>;
  /** `-ms-hyphenate-limit-chars` — a whole number, and this project's variables of that kind. */
  "-ms-hyphenate-limit-chars": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `-ms-hyphenate-limit-lines` — a whole number, and this project's variables of that kind. */
  "-ms-hyphenate-limit-lines": Narrowed<"no-limit", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `-ms-scroll-limit-x-max` — a length, and this project's variables of that kind. */
  "-ms-scroll-limit-x-max": Narrowed<"auto", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `-ms-scroll-limit-x-min` — a length, and this project's variables of that kind. */
  "-ms-scroll-limit-x-min": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `-ms-scroll-limit-y-max` — a length, and this project's variables of that kind. */
  "-ms-scroll-limit-y-max": Narrowed<"auto", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `-ms-scroll-limit-y-min` — a length, and this project's variables of that kind. */
  "-ms-scroll-limit-y-min": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `-ms-scrollbar-3dlight-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-3dlight-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-arrow-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-arrow-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-base-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-base-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-darkshadow-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-darkshadow-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-face-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-face-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-highlight-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-highlight-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-shadow-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-shadow-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-scrollbar-track-color` — a colour, and this project's variables of that kind. */
  "-ms-scrollbar-track-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-ms-wrap-margin` — a length, and this project's variables of that kind. */
  "-ms-wrap-margin": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `-webkit-border-before-color` — a colour, and this project's variables of that kind. */
  "-webkit-border-before-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-webkit-border-before-width` — a length, and this project's variables of that kind. */
  "-webkit-border-before-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `-webkit-line-clamp` — a whole number, and this project's variables of that kind. */
  "-webkit-line-clamp": Narrowed<"none", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `-webkit-mask-position-x` — a length or a percentage, and this project's variables of that kind. */
  "-webkit-mask-position-x": Narrowed<"center" | "left" | "right", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `-webkit-mask-position-y` — a length or a percentage, and this project's variables of that kind. */
  "-webkit-mask-position-y": Narrowed<"bottom" | "center" | "top", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `-webkit-mask-size` — a length or a percentage, and this project's variables of that kind. */
  "-webkit-mask-size": Narrowed<"auto" | "contain" | "cover", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `-webkit-tap-highlight-color` — a colour, and this project's variables of that kind. */
  "-webkit-tap-highlight-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-webkit-text-fill-color` — a colour, and this project's variables of that kind. */
  "-webkit-text-fill-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-webkit-text-stroke-color` — a colour, and this project's variables of that kind. */
  "-webkit-text-stroke-color": Narrowed<never, CssColor | Token<"color">>;
  /** `-webkit-text-stroke-width` — a length, and this project's variables of that kind. */
  "-webkit-text-stroke-width": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `accent-color` — a colour, and this project's variables of that kind. */
  "accent-color": Narrowed<"auto", CssColor | Token<"color">>;
  /** `animation-delay` — a time, and this project's variables of that kind. */
  "animation-delay": Narrowed<never, CssDimension<CssTimeUnit> | Token<"time">>;
  /** `animation-duration` — a time, and this project's variables of that kind. */
  "animation-duration": Narrowed<"auto", CssDimension<CssTimeUnit> | Token<"time">>;
  /** `animation-iteration-count` — a number, and this project's variables of that kind. */
  "animation-iteration-count": Narrowed<"infinite", number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `animation-range` — a length or a percentage, and this project's variables of that kind. */
  "animation-range": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `animation-range-end` — a length or a percentage, and this project's variables of that kind. */
  "animation-range-end": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `animation-range-start` — a length or a percentage, and this project's variables of that kind. */
  "animation-range-start": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `background-color` — a colour, and this project's variables of that kind. */
  "background-color": Narrowed<never, CssColor | Token<"color">>;
  /** `background-size` — a length or a percentage, and this project's variables of that kind. */
  "background-size": Narrowed<"auto" | "contain" | "cover", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `baseline-shift` — a length or a percentage, and this project's variables of that kind. */
  "baseline-shift": Narrowed<"baseline" | "sub" | "super", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `block-size` — a length or a percentage, and this project's variables of that kind. */
  "block-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `border-block-color` — a colour, and this project's variables of that kind. */
  "border-block-color": Narrowed<never, CssColor | Token<"color"> | `${string} ${string}`>;
  /** `border-block-end-color` — a colour, and this project's variables of that kind. */
  "border-block-end-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-block-end-width` — a length, and this project's variables of that kind. */
  "border-block-end-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-block-start-color` — a colour, and this project's variables of that kind. */
  "border-block-start-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-block-start-width` — a length, and this project's variables of that kind. */
  "border-block-start-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-block-width` — a length, and this project's variables of that kind. */
  "border-block-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `border-bottom-color` — a colour, and this project's variables of that kind. */
  "border-bottom-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-bottom-left-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-bottom-left-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `border-bottom-right-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-bottom-right-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `border-bottom-width` — a length, and this project's variables of that kind. */
  "border-bottom-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-color` — a colour, and this project's variables of that kind. */
  "border-color": Narrowed<never, CssColor | Token<"color"> | `${string} ${string}`>;
  /** `border-end-end-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-end-end-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `border-end-start-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-end-start-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `border-inline-color` — a colour, and this project's variables of that kind. */
  "border-inline-color": Narrowed<never, CssColor | Token<"color"> | `${string} ${string}`>;
  /** `border-inline-end-color` — a colour, and this project's variables of that kind. */
  "border-inline-end-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-inline-end-width` — a length, and this project's variables of that kind. */
  "border-inline-end-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-inline-start-color` — a colour, and this project's variables of that kind. */
  "border-inline-start-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-inline-start-width` — a length, and this project's variables of that kind. */
  "border-inline-start-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-inline-width` — a length, and this project's variables of that kind. */
  "border-inline-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `border-left-color` — a colour, and this project's variables of that kind. */
  "border-left-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-left-width` — a length, and this project's variables of that kind. */
  "border-left-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `border-right-color` — a colour, and this project's variables of that kind. */
  "border-right-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-right-width` — a length, and this project's variables of that kind. */
  "border-right-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-spacing` — a length, and this project's variables of that kind. */
  "border-spacing": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `border-start-end-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-start-end-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `border-start-start-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-start-start-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `border-top-color` — a colour, and this project's variables of that kind. */
  "border-top-color": Narrowed<never, CssColor | Token<"color">>;
  /** `border-top-left-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-top-left-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `border-top-right-radius` — a length or a percentage, and this project's variables of that kind. */
  "border-top-right-radius": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `border-top-width` — a length, and this project's variables of that kind. */
  "border-top-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `border-width` — a length, and this project's variables of that kind. */
  "border-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `bottom` — a length or a percentage, and this project's variables of that kind. */
  "bottom": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `box-flex` — a number, and this project's variables of that kind. */
  "box-flex": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `box-flex-group` — a whole number, and this project's variables of that kind. */
  "box-flex-group": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `box-ordinal-group` — a whole number, and this project's variables of that kind. */
  "box-ordinal-group": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `caret-color` — a colour, and this project's variables of that kind. */
  "caret-color": Narrowed<"auto", CssColor | Token<"color">>;
  /** `color` — a colour, and this project's variables of that kind. */
  "color": Narrowed<never, CssColor | Token<"color">>;
  /** `column-count` — a whole number, and this project's variables of that kind. */
  "column-count": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `column-gap` — a length or a percentage, and this project's variables of that kind. */
  "column-gap": Narrowed<"normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `column-height` — a length, and this project's variables of that kind. */
  "column-height": Narrowed<"auto", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `column-rule-color` — a colour, and this project's variables of that kind. */
  "column-rule-color": Narrowed<never, CssColor | Token<"color">>;
  /** `column-rule-width` — a length, and this project's variables of that kind. */
  "column-rule-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `column-width` — a length, and this project's variables of that kind. */
  "column-width": Narrowed<"auto", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `flex-basis` — a length or a percentage, and this project's variables of that kind. */
  "flex-basis": Narrowed<"auto" | "content" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `flex-grow` — a number, and this project's variables of that kind. */
  "flex-grow": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `flex-shrink` — a number, and this project's variables of that kind. */
  "flex-shrink": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `flood-color` — a colour, and this project's variables of that kind. */
  "flood-color": Narrowed<never, CssColor | Token<"color">>;
  /** `font-size` — a length or a percentage, and this project's variables of that kind. */
  "font-size": Narrowed<"large" | "larger" | "math" | "medium" | "small" | "smaller" | "x-large" | "x-small" | "xx-large" | "xx-small" | "xxx-large", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `font-smooth` — a length, and this project's variables of that kind. */
  "font-smooth": Narrowed<"always" | "auto" | "large" | "medium" | "never" | "small" | "x-large" | "x-small" | "xx-large" | "xx-small" | "xxx-large", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `font-stretch` — a percentage, and this project's variables of that kind. */
  "font-stretch": Narrowed<"condensed" | "expanded" | "extra-condensed" | "extra-expanded" | "normal" | "semi-condensed" | "semi-expanded" | "ultra-condensed" | "ultra-expanded", CssDimension<"%"> | Token<"percentage">>;
  /** `font-weight` — a number, and this project's variables of that kind. */
  "font-weight": Narrowed<"bold" | "bolder" | "lighter" | "normal", number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `font-width` — a percentage, and this project's variables of that kind. */
  "font-width": Narrowed<"condensed" | "expanded" | "extra-condensed" | "extra-expanded" | "normal" | "semi-condensed" | "semi-expanded" | "ultra-condensed" | "ultra-expanded", CssDimension<"%"> | Token<"percentage">>;
  /** `gap` — a length or a percentage, and this project's variables of that kind. */
  "gap": Narrowed<"normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `grid-column-gap` — a length or a percentage, and this project's variables of that kind. */
  "grid-column-gap": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `grid-gap` — a length or a percentage, and this project's variables of that kind. */
  "grid-gap": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `grid-row-gap` — a length or a percentage, and this project's variables of that kind. */
  "grid-row-gap": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `height` — a length or a percentage, and this project's variables of that kind. */
  "height": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `hyphenate-limit-chars` — a whole number, and this project's variables of that kind. */
  "hyphenate-limit-chars": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `inline-size` — a length or a percentage, and this project's variables of that kind. */
  "inline-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `inset` — a length or a percentage, and this project's variables of that kind. */
  "inset": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `inset-block` — a length or a percentage, and this project's variables of that kind. */
  "inset-block": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `inset-block-end` — a length or a percentage, and this project's variables of that kind. */
  "inset-block-end": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `inset-block-start` — a length or a percentage, and this project's variables of that kind. */
  "inset-block-start": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `inset-inline` — a length or a percentage, and this project's variables of that kind. */
  "inset-inline": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `inset-inline-end` — a length or a percentage, and this project's variables of that kind. */
  "inset-inline-end": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `inset-inline-start` — a length or a percentage, and this project's variables of that kind. */
  "inset-inline-start": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `interest-delay` — a time, and this project's variables of that kind. */
  "interest-delay": Narrowed<"normal", CssDimension<CssTimeUnit> | Token<"time"> | `${string} ${string}`>;
  /** `interest-delay-end` — a time, and this project's variables of that kind. */
  "interest-delay-end": Narrowed<"normal", CssDimension<CssTimeUnit> | Token<"time">>;
  /** `interest-delay-start` — a time, and this project's variables of that kind. */
  "interest-delay-start": Narrowed<"normal", CssDimension<CssTimeUnit> | Token<"time">>;
  /** `left` — a length or a percentage, and this project's variables of that kind. */
  "left": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `letter-spacing` — a length, and this project's variables of that kind. */
  "letter-spacing": Narrowed<"normal", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `lighting-color` — a colour, and this project's variables of that kind. */
  "lighting-color": Narrowed<never, CssColor | Token<"color">>;
  /** `line-clamp` — a whole number, and this project's variables of that kind. */
  "line-clamp": Narrowed<"none", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `line-height-step` — a length, and this project's variables of that kind. */
  "line-height-step": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `margin` — a length or a percentage, and this project's variables of that kind. */
  "margin": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `margin-block` — a length or a percentage, and this project's variables of that kind. */
  "margin-block": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `margin-block-end` — a length or a percentage, and this project's variables of that kind. */
  "margin-block-end": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-block-start` — a length or a percentage, and this project's variables of that kind. */
  "margin-block-start": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-bottom` — a length or a percentage, and this project's variables of that kind. */
  "margin-bottom": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-inline` — a length or a percentage, and this project's variables of that kind. */
  "margin-inline": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `margin-inline-end` — a length or a percentage, and this project's variables of that kind. */
  "margin-inline-end": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-inline-start` — a length or a percentage, and this project's variables of that kind. */
  "margin-inline-start": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-left` — a length or a percentage, and this project's variables of that kind. */
  "margin-left": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-right` — a length or a percentage, and this project's variables of that kind. */
  "margin-right": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `margin-top` — a length or a percentage, and this project's variables of that kind. */
  "margin-top": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `mask-size` — a length or a percentage, and this project's variables of that kind. */
  "mask-size": Narrowed<"auto" | "contain" | "cover", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `math-depth` — a whole number, and this project's variables of that kind. */
  "math-depth": Narrowed<"auto-add", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `max-block-size` — a length or a percentage, and this project's variables of that kind. */
  "max-block-size": Narrowed<"fit-content" | "max-content" | "min-content" | "none", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `max-height` — a length or a percentage, and this project's variables of that kind. */
  "max-height": Narrowed<"fit-content" | "max-content" | "min-content" | "none", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `max-inline-size` — a length or a percentage, and this project's variables of that kind. */
  "max-inline-size": Narrowed<"fit-content" | "max-content" | "min-content" | "none", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `max-lines` — a whole number, and this project's variables of that kind. */
  "max-lines": Narrowed<"none", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `max-width` — a length or a percentage, and this project's variables of that kind. */
  "max-width": Narrowed<"fit-content" | "max-content" | "min-content" | "none", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `min-block-size` — a length or a percentage, and this project's variables of that kind. */
  "min-block-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `min-height` — a length or a percentage, and this project's variables of that kind. */
  "min-height": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `min-inline-size` — a length or a percentage, and this project's variables of that kind. */
  "min-inline-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `min-width` — a length or a percentage, and this project's variables of that kind. */
  "min-width": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `offset-distance` — a length or a percentage, and this project's variables of that kind. */
  "offset-distance": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `order` — a whole number, and this project's variables of that kind. */
  "order": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `orphans` — a whole number, and this project's variables of that kind. */
  "orphans": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `outline-color` — a colour, and this project's variables of that kind. */
  "outline-color": Narrowed<"auto", CssColor | Token<"color">>;
  /** `outline-offset` — a length, and this project's variables of that kind. */
  "outline-offset": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `outline-width` — a length, and this project's variables of that kind. */
  "outline-width": Narrowed<"medium" | "thick" | "thin", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `padding` — a length or a percentage, and this project's variables of that kind. */
  "padding": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `padding-block` — a length or a percentage, and this project's variables of that kind. */
  "padding-block": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `padding-block-end` — a length or a percentage, and this project's variables of that kind. */
  "padding-block-end": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-block-start` — a length or a percentage, and this project's variables of that kind. */
  "padding-block-start": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-bottom` — a length or a percentage, and this project's variables of that kind. */
  "padding-bottom": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-inline` — a length or a percentage, and this project's variables of that kind. */
  "padding-inline": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}`>;
  /** `padding-inline-end` — a length or a percentage, and this project's variables of that kind. */
  "padding-inline-end": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-inline-start` — a length or a percentage, and this project's variables of that kind. */
  "padding-inline-start": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-left` — a length or a percentage, and this project's variables of that kind. */
  "padding-left": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-right` — a length or a percentage, and this project's variables of that kind. */
  "padding-right": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `padding-top` — a length or a percentage, and this project's variables of that kind. */
  "padding-top": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `perspective` — a length, and this project's variables of that kind. */
  "perspective": Narrowed<"none", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `reading-order` — a whole number, and this project's variables of that kind. */
  "reading-order": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `right` — a length or a percentage, and this project's variables of that kind. */
  "right": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `row-gap` — a length or a percentage, and this project's variables of that kind. */
  "row-gap": Narrowed<"normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-margin` — a length, and this project's variables of that kind. */
  "scroll-margin": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `scroll-margin-block` — a length, and this project's variables of that kind. */
  "scroll-margin-block": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `scroll-margin-block-end` — a length, and this project's variables of that kind. */
  "scroll-margin-block-end": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-block-start` — a length, and this project's variables of that kind. */
  "scroll-margin-block-start": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-bottom` — a length, and this project's variables of that kind. */
  "scroll-margin-bottom": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-inline` — a length, and this project's variables of that kind. */
  "scroll-margin-inline": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length"> | `${string} ${string}`>;
  /** `scroll-margin-inline-end` — a length, and this project's variables of that kind. */
  "scroll-margin-inline-end": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-inline-start` — a length, and this project's variables of that kind. */
  "scroll-margin-inline-start": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-left` — a length, and this project's variables of that kind. */
  "scroll-margin-left": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-right` — a length, and this project's variables of that kind. */
  "scroll-margin-right": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-margin-top` — a length, and this project's variables of that kind. */
  "scroll-margin-top": Narrowed<never, CssDimension<CssLengthUnit> | Token<"length">>;
  /** `scroll-padding` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-block` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-block": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-block-end` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-block-end": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-block-start` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-block-start": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-bottom` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-bottom": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-inline` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-inline": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-inline-end` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-inline-end": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-inline-start` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-inline-start": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-left` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-left": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-right` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-right": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scroll-padding-top` — a length or a percentage, and this project's variables of that kind. */
  "scroll-padding-top": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `scrollbar-color` — a colour, and this project's variables of that kind. */
  "scrollbar-color": Narrowed<"auto", CssColor | Token<"color">>;
  /** `shape-margin` — a length or a percentage, and this project's variables of that kind. */
  "shape-margin": Narrowed<never, CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `stop-color` — a colour, and this project's variables of that kind. */
  "stop-color": Narrowed<never, CssColor | Token<"color">>;
  /** `stroke-color` — a colour, and this project's variables of that kind. */
  "stroke-color": Narrowed<never, CssColor | Token<"color">>;
  /** `stroke-miterlimit` — a number, and this project's variables of that kind. */
  "stroke-miterlimit": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `text-decoration-color` — a colour, and this project's variables of that kind. */
  "text-decoration-color": Narrowed<never, CssColor | Token<"color">>;
  /** `text-decoration-inset` — a length, and this project's variables of that kind. */
  "text-decoration-inset": Narrowed<"auto", CssDimension<CssLengthUnit> | Token<"length">>;
  /** `text-emphasis-color` — a colour, and this project's variables of that kind. */
  "text-emphasis-color": Narrowed<never, CssColor | Token<"color">>;
  /** `text-size-adjust` — a percentage, and this project's variables of that kind. */
  "text-size-adjust": Narrowed<"auto" | "none", CssDimension<"%"> | Token<"percentage">>;
  /** `timeline-trigger-exit-range` — a length or a percentage, and this project's variables of that kind. */
  "timeline-trigger-exit-range": Narrowed<"auto" | "contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `timeline-trigger-exit-range-end` — a length or a percentage, and this project's variables of that kind. */
  "timeline-trigger-exit-range-end": Narrowed<"auto" | "contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `timeline-trigger-exit-range-start` — a length or a percentage, and this project's variables of that kind. */
  "timeline-trigger-exit-range-start": Narrowed<"auto" | "contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `timeline-trigger-range` — a length or a percentage, and this project's variables of that kind. */
  "timeline-trigger-range": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `timeline-trigger-range-end` — a length or a percentage, and this project's variables of that kind. */
  "timeline-trigger-range-end": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `timeline-trigger-range-start` — a length or a percentage, and this project's variables of that kind. */
  "timeline-trigger-range-start": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `top` — a length or a percentage, and this project's variables of that kind. */
  "top": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `transition-delay` — a time, and this project's variables of that kind. */
  "transition-delay": Narrowed<never, CssDimension<CssTimeUnit> | Token<"time">>;
  /** `transition-duration` — a time, and this project's variables of that kind. */
  "transition-duration": Narrowed<never, CssDimension<CssTimeUnit> | Token<"time">>;
  /** `view-timeline-inset` — a length or a percentage, and this project's variables of that kind. */
  "view-timeline-inset": Narrowed<"auto", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `widows` — a whole number, and this project's variables of that kind. */
  "widows": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `width` — a length or a percentage, and this project's variables of that kind. */
  "width": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", CssDimension<CssLengthUnit | "%"> | Token<"length" | "length-percentage" | "percentage">>;
  /** `word-spacing` — a length, and this project's variables of that kind. */
  "word-spacing": Narrowed<"normal", CssDimension<CssLengthUnit> | Token<"length">>;
}

/** What this project's blocks are checked against — the shipped map, with those replaced. */
export type CssProperties = Omit<Base, keyof Narrowings> & Narrowings;

/** The shape of one block here. The virtual file reads this. */
export type CssBlockShape = Partial<CssProperties> & {
  [nested: `&${string}`]: CssBlockShape[];
} & { [at: `@${string}`]: CssBlockShape[] } & { [dashed: `-${string}`]: CssValue };
export type {
  CssBlock,
  CssCondition,
  CssFontFaceDescriptors,
  CssGlobal,
  CssKeyframesShape,
  CssPropertyDescriptors,
  CssSpreadable,
  CssValue,
  Keyword,
  Narrowed,
  StyleValue,
};

/** What one property accepts in this project — `const gap: Value<"padding-left"> = "8px"`. */
export type Value<P extends keyof CssProperties> = CssProperties[P];

/** Every variable this project declares, by kind — what `Var` reads. */
export interface VarByKind {
  "color": typeof $.color.accent.main | typeof $.color.accent.quiet | typeof $.color.surface.base | typeof $.color.surface.sunken | typeof $.color.text.primary | typeof $.color.text.muted;
  "length": typeof $.space.gutter.tight | typeof $.space.gutter.normal | typeof $.space.gutter.wide | typeof $.size.radius.small | typeof $.size.radius.pill;
  "time": typeof $.motion.quick | typeof $.motion.calm;
}

/** Any variable of a kind — `const tone: Var<"color"> = toggle ? $.a.b : $.a.c`. */
export type Var<K extends keyof VarByKind> = VarByKind[K];
