// Generated by scripts/build-engine-keywords.mjs. Do not edit.
//
// Values an engine accepts for a property whose union mdn-data closed without them — legacy and
// SVG spellings, mostly. Refusing one would be refusing valid CSS, which is the one failure a
// type map may not have.
//
// chromium     14
// firefox      14
// webkit       13
// the union    20 across 13 properties

/** Property -> the extra values, beside what its `Keyword<…>` union already holds. */
export const ENGINE_KEYWORDS: Readonly<Record<string, readonly string[]>> = {
  "alignment-baseline": ["auto","hanging","text-bottom","text-top"],
  "dominant-baseline": ["text-after-edge","text-before-edge"],
  "flex-wrap": ["balance"],
  "image-rendering": ["optimizeSpeed"],
  "margin-trim": ["block","inline"],
  "overflow-anchor": ["visible"],
  "overflow-block": ["overlay"],
  "overflow-inline": ["overlay"],
  "overflow-x": ["overlay"],
  "overflow-y": ["overlay"],
  "text-align-last": ["match-parent"],
  "word-wrap": ["anywhere"],
  "writing-mode": ["lr","rl","tb"],
};
