/* Generated by @ramonda/css from ramonda.css.ts. Do not edit. */
/* To change it, edit ramonda.css.ts and run `ramonda-css codegen`. */

import type { CssColor, CssDimension, CssLengthUnit, CssTimeUnit, Fixed, Token } from "@ramonda/css";
import type { CssProperties as Base, CssBlock, CssCondition, CssFontFaceDescriptors, CssGlobal, CssKeyframesShape, CssPropertyDescriptors, CssRegistered, CssSpreadable, CssValue, CssVar, Keyword, Narrowed, StyleValue } from "@ramonda/css/properties";

/** The `color` tokens, as a block writes them: `$color.…`. */
export const $color = Object.freeze({
  /**
   * `$color.page` — a `color`, written to CSS as `var(--color-page)`.
   *
   * Starts as `light-dark(#fbf8ff, #14101a)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "page": "var(--color-page)" as Token<"color", Fixed<"light-dark(#fbf8ff, #14101a)">>,
  /**
   * `$color.text` — a `color`, written to CSS as `var(--color-text)`.
   *
   * Starts as `light-dark(#241a2e, #ece6f3)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "text": "var(--color-text)" as Token<"color", Fixed<"light-dark(#241a2e, #ece6f3)">>,
  /**
   * `$color.muted` — a `color`, written to CSS as `var(--color-muted)`.
   *
   * Starts as `light-dark(#6b6376, #a79fb3)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "muted": "var(--color-muted)" as Token<"color", Fixed<"light-dark(#6b6376, #a79fb3)">>,
  /**
   * `$color.accent` — a `color`, written to CSS as `var(--color-accent)`.
   *
   * Starts as `light-dark(#7a4fbf, #b18ae6)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "accent": "var(--color-accent)" as Token<"color", Fixed<"light-dark(#7a4fbf, #b18ae6)">>,
  /**
   * `$color.onAccent` — a `color`, written to CSS as `var(--color-onAccent)`.
   *
   * Starts as `#ffffff`. Fixed: declared without a `range`, so nothing may set it.
   */
  "onAccent": "var(--color-onAccent)" as Token<"color", Fixed<"#ffffff">>,
  /**
   * `$color.surface` — a `color`, written to CSS as `var(--color-surface)`.
   *
   * Starts as `light-dark(#ffffff, #1e1826)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "surface": "var(--color-surface)" as Token<"color", Fixed<"light-dark(#ffffff, #1e1826)">>,
  /**
   * `$color.line` — a `color`, written to CSS as `var(--color-line)`.
   *
   * Starts as `light-dark(#ece3f5, #2e2739)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "line": "var(--color-line)" as Token<"color", Fixed<"light-dark(#ece3f5, #2e2739)">>,
  /**
   * `$color.code` — a `color`, written to CSS as `var(--color-code)`.
   *
   * Starts as `light-dark(#efe8f8, #2a2236)`. Fixed: declared without a `range`, so nothing may set it.
   */
  "code": "var(--color-code)" as Token<"color", Fixed<"light-dark(#efe8f8, #2a2236)">>,
});

/** The `space` tokens, as a block writes them: `$space.…`. */
export const $space = Object.freeze({
  /**
   * `$space.xs` — a `length`, written to CSS as `var(--space-xs)`.
   *
   * Starts as `2px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "xs": "var(--space-xs)" as Token<"length", Fixed<"2px">>,
  /**
   * `$space.s` — a `length`, written to CSS as `var(--space-s)`.
   *
   * Starts as `8px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "s": "var(--space-s)" as Token<"length", Fixed<"8px">>,
  /**
   * `$space.m` — a `length`, written to CSS as `var(--space-m)`.
   *
   * Starts as `12px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "m": "var(--space-m)" as Token<"length", Fixed<"12px">>,
  /**
   * `$space.l` — a `length`, written to CSS as `var(--space-l)`.
   *
   * Starts as `24px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "l": "var(--space-l)" as Token<"length", Fixed<"24px">>,
  /**
   * `$space.xl` — a `length`, written to CSS as `var(--space-xl)`.
   *
   * Starts as `40px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "xl": "var(--space-xl)" as Token<"length", Fixed<"40px">>,
});

/** The `size` tokens, as a block writes them: `$size.…`. */
export const $size = Object.freeze({
  /**
   * `$size.line` — a `length`, written to CSS as `var(--size-line)`.
   *
   * Starts as `1px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "line": "var(--size-line)" as Token<"length", Fixed<"1px">>,
  /**
   * `$size.focus` — a `length`, written to CSS as `var(--size-focus)`.
   *
   * Starts as `3px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "focus": "var(--size-focus)" as Token<"length", Fixed<"3px">>,
  /**
   * `$size.card` — a `length`, written to CSS as `var(--size-card)`.
   *
   * Starts as `480px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "card": "var(--size-card)" as Token<"length", Fixed<"480px">>,
  /**
   * `$size.column` — a `length`, written to CSS as `var(--size-column)`.
   *
   * Starts as `672px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "column": "var(--size-column)" as Token<"length", Fixed<"672px">>,
  /**
   * `$size.screen` — a `length`, written to CSS as `var(--size-screen)`.
   *
   * Starts as `100vh`. Fixed: declared without a `range`, so nothing may set it.
   */
  "screen": "var(--size-screen)" as Token<"length", Fixed<"100vh">>,
});

/** The `radius` tokens, as a block writes them: `$radius.…`. */
export const $radius = Object.freeze({
  /**
   * `$radius.s` — a `length`, written to CSS as `var(--radius-s)`.
   *
   * Starts as `5px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "s": "var(--radius-s)" as Token<"length", Fixed<"5px">>,
  /**
   * `$radius.m` — a `length`, written to CSS as `var(--radius-m)`.
   *
   * Starts as `10px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "m": "var(--radius-m)" as Token<"length", Fixed<"10px">>,
  /**
   * `$radius.l` — a `length`, written to CSS as `var(--radius-l)`.
   *
   * Starts as `16px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "l": "var(--radius-l)" as Token<"length", Fixed<"16px">>,
});

/** The `font` tokens, as a block writes them: `$font.…`. */
export const $font = Object.freeze({
  /**
   * `$font.s` — a `length`, written to CSS as `var(--font-s)`.
   *
   * Starts as `14px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "s": "var(--font-s)" as Token<"length", Fixed<"14px">>,
  /**
   * `$font.l` — a `length`, written to CSS as `var(--font-l)`.
   *
   * Starts as `36px`. Fixed: declared without a `range`, so nothing may set it.
   */
  "l": "var(--font-l)" as Token<"length", Fixed<"36px">>,
});

/** The 215 properties this project narrows, and what each takes. */
interface Narrowings {
  /** `-moz-border-bottom-colors` — a colour, and only as one of this project's tokens. */
  "-moz-border-bottom-colors": Narrowed<"none" | "currentcolor", Token<"color">>;
  /** `-moz-border-left-colors` — a colour, and only as one of this project's tokens. */
  "-moz-border-left-colors": Narrowed<"none" | "currentcolor", Token<"color">>;
  /** `-moz-border-right-colors` — a colour, and only as one of this project's tokens. */
  "-moz-border-right-colors": Narrowed<"none" | "currentcolor", Token<"color">>;
  /** `-moz-border-top-colors` — a colour, and only as one of this project's tokens. */
  "-moz-border-top-colors": Narrowed<"none" | "currentcolor", Token<"color">>;
  /** `-ms-content-zoom-limit-max` — a percentage, and this project's tokens of that kind. */
  "-ms-content-zoom-limit-max": Narrowed<never, CssDimension<"%"> | Token<"percentage">>;
  /** `-ms-content-zoom-limit-min` — a percentage, and this project's tokens of that kind. */
  "-ms-content-zoom-limit-min": Narrowed<never, CssDimension<"%"> | Token<"percentage">>;
  /** `-ms-hyphenate-limit-chars` — a whole number, and this project's tokens of that kind. */
  "-ms-hyphenate-limit-chars": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `-ms-hyphenate-limit-lines` — a whole number, and this project's tokens of that kind. */
  "-ms-hyphenate-limit-lines": Narrowed<"no-limit", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `-ms-scroll-limit-x-max` — a length, and only as one of this project's tokens. */
  "-ms-scroll-limit-x-max": Narrowed<"auto", Token<"length"> | 0 | "0">;
  /** `-ms-scroll-limit-x-min` — a length, and only as one of this project's tokens. */
  "-ms-scroll-limit-x-min": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `-ms-scroll-limit-y-max` — a length, and only as one of this project's tokens. */
  "-ms-scroll-limit-y-max": Narrowed<"auto", Token<"length"> | 0 | "0">;
  /** `-ms-scroll-limit-y-min` — a length, and only as one of this project's tokens. */
  "-ms-scroll-limit-y-min": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `-ms-scrollbar-3dlight-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-3dlight-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-arrow-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-arrow-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-base-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-base-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-darkshadow-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-darkshadow-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-face-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-face-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-highlight-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-highlight-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-shadow-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-shadow-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-scrollbar-track-color` — a colour, and only as one of this project's tokens. */
  "-ms-scrollbar-track-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-ms-wrap-margin` — a length, and only as one of this project's tokens. */
  "-ms-wrap-margin": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `-webkit-border-after-color` — a colour, and only as one of this project's tokens. */
  "-webkit-border-after-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-border-after-width` — a length, and only as one of this project's tokens. */
  "-webkit-border-after-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `-webkit-border-before-color` — a colour, and only as one of this project's tokens. */
  "-webkit-border-before-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-border-before-width` — a length, and only as one of this project's tokens. */
  "-webkit-border-before-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `-webkit-border-end-color` — a colour, and only as one of this project's tokens. */
  "-webkit-border-end-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-border-end-width` — a length, and only as one of this project's tokens. */
  "-webkit-border-end-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `-webkit-border-start-color` — a colour, and only as one of this project's tokens. */
  "-webkit-border-start-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-border-start-width` — a length, and only as one of this project's tokens. */
  "-webkit-border-start-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `-webkit-line-clamp` — a whole number, and this project's tokens of that kind. */
  "-webkit-line-clamp": Narrowed<"none", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `-webkit-mask-position-x` — a length or a percentage, and only as one of this project's tokens. */
  "-webkit-mask-position-x": Narrowed<"center" | "left" | "right", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `-webkit-mask-position-y` — a length or a percentage, and only as one of this project's tokens. */
  "-webkit-mask-position-y": Narrowed<"bottom" | "center" | "top", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `-webkit-mask-size` — a length or a percentage, and only as one of this project's tokens. */
  "-webkit-mask-size": Narrowed<"auto" | "contain" | "cover", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `-webkit-tap-highlight-color` — a colour, and only as one of this project's tokens. */
  "-webkit-tap-highlight-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-text-fill-color` — a colour, and only as one of this project's tokens. */
  "-webkit-text-fill-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-text-stroke-color` — a colour, and only as one of this project's tokens. */
  "-webkit-text-stroke-color": Narrowed<"currentcolor", Token<"color">>;
  /** `-webkit-text-stroke-width` — a length, and only as one of this project's tokens. */
  "-webkit-text-stroke-width": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `accent-color` — a colour, and only as one of this project's tokens. */
  "accent-color": Narrowed<"auto" | "currentcolor", Token<"color">>;
  /** `animation-delay` — a time, and this project's tokens of that kind. */
  "animation-delay": Narrowed<never, CssDimension<CssTimeUnit> | Token<"time">>;
  /** `animation-duration` — a time, and this project's tokens of that kind. */
  "animation-duration": Narrowed<"auto", CssDimension<CssTimeUnit> | Token<"time">>;
  /** `animation-iteration-count` — a number, and this project's tokens of that kind. */
  "animation-iteration-count": Narrowed<"infinite", number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `animation-range` — a length or a percentage, and only as one of this project's tokens. */
  "animation-range": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `animation-range-end` — a length or a percentage, and only as one of this project's tokens. */
  "animation-range-end": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `animation-range-start` — a length or a percentage, and only as one of this project's tokens. */
  "animation-range-start": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `background-color` — a colour, and only as one of this project's tokens. */
  "background-color": Narrowed<"currentcolor", Token<"color">>;
  /** `background-size` — a length or a percentage, and only as one of this project's tokens. */
  "background-size": Narrowed<"auto" | "contain" | "cover", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `baseline-shift` — a length or a percentage, and only as one of this project's tokens. */
  "baseline-shift": Narrowed<"baseline" | "sub" | "super", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `block-size` — a length or a percentage, and only as one of this project's tokens. */
  "block-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `border-block-color` — a colour, and only as one of this project's tokens. */
  "border-block-color": Narrowed<"currentcolor", Token<"color"> | `${string} ${string}`>;
  /** `border-block-end-color` — a colour, and only as one of this project's tokens. */
  "border-block-end-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-block-end-width` — a length, and only as one of this project's tokens. */
  "border-block-end-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-block-start-color` — a colour, and only as one of this project's tokens. */
  "border-block-start-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-block-start-width` — a length, and only as one of this project's tokens. */
  "border-block-start-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-block-width` — a length, and only as one of this project's tokens. */
  "border-block-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `border-bottom-color` — a colour, and only as one of this project's tokens. */
  "border-bottom-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-bottom-left-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-bottom-left-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `border-bottom-right-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-bottom-right-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `border-bottom-width` — a length, and only as one of this project's tokens. */
  "border-bottom-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-color` — a colour, and only as one of this project's tokens. */
  "border-color": Narrowed<"currentcolor", Token<"color"> | `${string} ${string}`>;
  /** `border-end-end-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-end-end-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `border-end-start-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-end-start-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `border-inline-color` — a colour, and only as one of this project's tokens. */
  "border-inline-color": Narrowed<"currentcolor", Token<"color"> | `${string} ${string}`>;
  /** `border-inline-end-color` — a colour, and only as one of this project's tokens. */
  "border-inline-end-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-inline-end-width` — a length, and only as one of this project's tokens. */
  "border-inline-end-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-inline-start-color` — a colour, and only as one of this project's tokens. */
  "border-inline-start-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-inline-start-width` — a length, and only as one of this project's tokens. */
  "border-inline-start-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-inline-width` — a length, and only as one of this project's tokens. */
  "border-inline-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `border-left-color` — a colour, and only as one of this project's tokens. */
  "border-left-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-left-width` — a length, and only as one of this project's tokens. */
  "border-left-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `border-right-color` — a colour, and only as one of this project's tokens. */
  "border-right-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-right-width` — a length, and only as one of this project's tokens. */
  "border-right-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-spacing` — a length, and only as one of this project's tokens. */
  "border-spacing": Narrowed<never, Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `border-start-end-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-start-end-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `border-start-start-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-start-start-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `border-top-color` — a colour, and only as one of this project's tokens. */
  "border-top-color": Narrowed<"currentcolor", Token<"color">>;
  /** `border-top-left-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-top-left-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `border-top-right-radius` — a length or a percentage, and only as one of this project's tokens. */
  "border-top-right-radius": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `border-top-width` — a length, and only as one of this project's tokens. */
  "border-top-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `border-width` — a length, and only as one of this project's tokens. */
  "border-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `bottom` — a length or a percentage, and only as one of this project's tokens. */
  "bottom": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `box-flex` — a number, and this project's tokens of that kind. */
  "box-flex": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `box-flex-group` — a whole number, and this project's tokens of that kind. */
  "box-flex-group": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `box-ordinal-group` — a whole number, and this project's tokens of that kind. */
  "box-ordinal-group": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `caret-color` — a colour, and only as one of this project's tokens. */
  "caret-color": Narrowed<"auto" | "currentcolor", Token<"color">>;
  /** `color` — a colour, and only as one of this project's tokens. */
  "color": Narrowed<"currentcolor", Token<"color">>;
  /** `column-count` — a whole number, and this project's tokens of that kind. */
  "column-count": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `column-gap` — a length or a percentage, and only as one of this project's tokens. */
  "column-gap": Narrowed<"normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `column-height` — a length, and only as one of this project's tokens. */
  "column-height": Narrowed<"auto", Token<"length"> | 0 | "0">;
  /** `column-rule-color` — a colour, and only as one of this project's tokens. */
  "column-rule-color": Narrowed<"currentcolor", Token<"color">>;
  /** `column-rule-width` — a length, and only as one of this project's tokens. */
  "column-rule-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `column-width` — a length, and only as one of this project's tokens. */
  "column-width": Narrowed<"auto", Token<"length"> | 0 | "0">;
  /** `flex-basis` — a length or a percentage, and only as one of this project's tokens. */
  "flex-basis": Narrowed<"auto" | "content" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `flex-grow` — a number, and this project's tokens of that kind. */
  "flex-grow": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `flex-line-count` — a whole number, and this project's tokens of that kind. */
  "flex-line-count": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `flex-shrink` — a number, and this project's tokens of that kind. */
  "flex-shrink": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `flood-color` — a colour, and only as one of this project's tokens. */
  "flood-color": Narrowed<"currentcolor", Token<"color">>;
  /** `font-size` — a length or a percentage, and only as one of this project's tokens. */
  "font-size": Narrowed<"large" | "larger" | "math" | "medium" | "small" | "smaller" | "x-large" | "x-small" | "xx-large" | "xx-small" | "xxx-large", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `font-smooth` — a length, and only as one of this project's tokens. */
  "font-smooth": Narrowed<"always" | "auto" | "large" | "medium" | "never" | "small" | "x-large" | "x-small" | "xx-large" | "xx-small" | "xxx-large", Token<"length"> | 0 | "0">;
  /** `font-stretch` — a percentage, and this project's tokens of that kind. */
  "font-stretch": Narrowed<"condensed" | "expanded" | "extra-condensed" | "extra-expanded" | "normal" | "semi-condensed" | "semi-expanded" | "ultra-condensed" | "ultra-expanded", CssDimension<"%"> | Token<"percentage">>;
  /** `font-weight` — a number, and this project's tokens of that kind. */
  "font-weight": Narrowed<"bold" | "bolder" | "lighter" | "normal", number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `font-width` — a percentage, and this project's tokens of that kind. */
  "font-width": Narrowed<"condensed" | "expanded" | "extra-condensed" | "extra-expanded" | "normal" | "semi-condensed" | "semi-expanded" | "ultra-condensed" | "ultra-expanded", CssDimension<"%"> | Token<"percentage">>;
  /** `gap` — a length or a percentage, and only as one of this project's tokens. */
  "gap": Narrowed<"normal", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `grid-column-gap` — a length or a percentage, and only as one of this project's tokens. */
  "grid-column-gap": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `grid-gap` — a length or a percentage, and only as one of this project's tokens. */
  "grid-gap": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `grid-row-gap` — a length or a percentage, and only as one of this project's tokens. */
  "grid-row-gap": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `height` — a length or a percentage, and only as one of this project's tokens. */
  "height": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `hyphenate-limit-chars` — a whole number, and this project's tokens of that kind. */
  "hyphenate-limit-chars": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `inline-size` — a length or a percentage, and only as one of this project's tokens. */
  "inline-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `inset` — a length or a percentage, and only as one of this project's tokens. */
  "inset": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `inset-block` — a length or a percentage, and only as one of this project's tokens. */
  "inset-block": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `inset-block-end` — a length or a percentage, and only as one of this project's tokens. */
  "inset-block-end": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `inset-block-start` — a length or a percentage, and only as one of this project's tokens. */
  "inset-block-start": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `inset-inline` — a length or a percentage, and only as one of this project's tokens. */
  "inset-inline": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `inset-inline-end` — a length or a percentage, and only as one of this project's tokens. */
  "inset-inline-end": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `inset-inline-start` — a length or a percentage, and only as one of this project's tokens. */
  "inset-inline-start": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `interest-delay` — a time, and this project's tokens of that kind. */
  "interest-delay": Narrowed<"normal", CssDimension<CssTimeUnit> | Token<"time"> | `${string} ${string}`>;
  /** `interest-delay-end` — a time, and this project's tokens of that kind. */
  "interest-delay-end": Narrowed<"normal", CssDimension<CssTimeUnit> | Token<"time">>;
  /** `interest-delay-start` — a time, and this project's tokens of that kind. */
  "interest-delay-start": Narrowed<"normal", CssDimension<CssTimeUnit> | Token<"time">>;
  /** `left` — a length or a percentage, and only as one of this project's tokens. */
  "left": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `letter-spacing` — a length, and only as one of this project's tokens. */
  "letter-spacing": Narrowed<"normal", Token<"length"> | 0 | "0">;
  /** `lighting-color` — a colour, and only as one of this project's tokens. */
  "lighting-color": Narrowed<"currentcolor", Token<"color">>;
  /** `line-clamp` — a whole number, and this project's tokens of that kind. */
  "line-clamp": Narrowed<"none", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `line-height-step` — a length, and only as one of this project's tokens. */
  "line-height-step": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `margin` — a length or a percentage, and only as one of this project's tokens. */
  "margin": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `margin-block` — a length or a percentage, and only as one of this project's tokens. */
  "margin-block": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `margin-block-end` — a length or a percentage, and only as one of this project's tokens. */
  "margin-block-end": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-block-start` — a length or a percentage, and only as one of this project's tokens. */
  "margin-block-start": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-bottom` — a length or a percentage, and only as one of this project's tokens. */
  "margin-bottom": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-inline` — a length or a percentage, and only as one of this project's tokens. */
  "margin-inline": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `margin-inline-end` — a length or a percentage, and only as one of this project's tokens. */
  "margin-inline-end": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-inline-start` — a length or a percentage, and only as one of this project's tokens. */
  "margin-inline-start": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-left` — a length or a percentage, and only as one of this project's tokens. */
  "margin-left": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-right` — a length or a percentage, and only as one of this project's tokens. */
  "margin-right": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `margin-top` — a length or a percentage, and only as one of this project's tokens. */
  "margin-top": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `mask-size` — a length or a percentage, and only as one of this project's tokens. */
  "mask-size": Narrowed<"auto" | "contain" | "cover", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `math-depth` — a whole number, and this project's tokens of that kind. */
  "math-depth": Narrowed<"auto-add", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `max-block-size` — a length or a percentage, and only as one of this project's tokens. */
  "max-block-size": Narrowed<"fit-content" | "max-content" | "min-content" | "none", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `max-height` — a length or a percentage, and only as one of this project's tokens. */
  "max-height": Narrowed<"fit-content" | "max-content" | "min-content" | "none", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `max-inline-size` — a length or a percentage, and only as one of this project's tokens. */
  "max-inline-size": Narrowed<"fit-content" | "max-content" | "min-content" | "none", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `max-lines` — a whole number, and this project's tokens of that kind. */
  "max-lines": Narrowed<"none", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `max-width` — a length or a percentage, and only as one of this project's tokens. */
  "max-width": Narrowed<"fit-content" | "max-content" | "min-content" | "none", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `min-block-size` — a length or a percentage, and only as one of this project's tokens. */
  "min-block-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `min-height` — a length or a percentage, and only as one of this project's tokens. */
  "min-height": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `min-inline-size` — a length or a percentage, and only as one of this project's tokens. */
  "min-inline-size": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `min-width` — a length or a percentage, and only as one of this project's tokens. */
  "min-width": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `offset-distance` — a length or a percentage, and only as one of this project's tokens. */
  "offset-distance": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `order` — a whole number, and this project's tokens of that kind. */
  "order": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `orphans` — a whole number, and this project's tokens of that kind. */
  "orphans": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `outline-color` — a colour, and only as one of this project's tokens. */
  "outline-color": Narrowed<"auto" | "currentcolor", Token<"color">>;
  /** `outline-offset` — a length, and only as one of this project's tokens. */
  "outline-offset": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `outline-width` — a length, and only as one of this project's tokens. */
  "outline-width": Narrowed<"medium" | "thick" | "thin", Token<"length"> | 0 | "0">;
  /** `padding` — a length or a percentage, and only as one of this project's tokens. */
  "padding": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `padding-block` — a length or a percentage, and only as one of this project's tokens. */
  "padding-block": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `padding-block-end` — a length or a percentage, and only as one of this project's tokens. */
  "padding-block-end": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-block-start` — a length or a percentage, and only as one of this project's tokens. */
  "padding-block-start": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-bottom` — a length or a percentage, and only as one of this project's tokens. */
  "padding-bottom": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-inline` — a length or a percentage, and only as one of this project's tokens. */
  "padding-inline": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | `${string} ${string}` | 0 | "0">;
  /** `padding-inline-end` — a length or a percentage, and only as one of this project's tokens. */
  "padding-inline-end": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-inline-start` — a length or a percentage, and only as one of this project's tokens. */
  "padding-inline-start": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-left` — a length or a percentage, and only as one of this project's tokens. */
  "padding-left": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-right` — a length or a percentage, and only as one of this project's tokens. */
  "padding-right": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `padding-top` — a length or a percentage, and only as one of this project's tokens. */
  "padding-top": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `perspective` — a length, and only as one of this project's tokens. */
  "perspective": Narrowed<"none", Token<"length"> | 0 | "0">;
  /** `reading-order` — a whole number, and this project's tokens of that kind. */
  "reading-order": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `right` — a length or a percentage, and only as one of this project's tokens. */
  "right": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `row-gap` — a length or a percentage, and only as one of this project's tokens. */
  "row-gap": Narrowed<"normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `rx` — a length or a percentage, and only as one of this project's tokens. */
  "rx": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `ry` — a length or a percentage, and only as one of this project's tokens. */
  "ry": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-margin` — a length, and only as one of this project's tokens. */
  "scroll-margin": Narrowed<never, Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `scroll-margin-block` — a length, and only as one of this project's tokens. */
  "scroll-margin-block": Narrowed<never, Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `scroll-margin-block-end` — a length, and only as one of this project's tokens. */
  "scroll-margin-block-end": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-block-start` — a length, and only as one of this project's tokens. */
  "scroll-margin-block-start": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-bottom` — a length, and only as one of this project's tokens. */
  "scroll-margin-bottom": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-inline` — a length, and only as one of this project's tokens. */
  "scroll-margin-inline": Narrowed<never, Token<"length"> | `${string} ${string}` | 0 | "0">;
  /** `scroll-margin-inline-end` — a length, and only as one of this project's tokens. */
  "scroll-margin-inline-end": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-inline-start` — a length, and only as one of this project's tokens. */
  "scroll-margin-inline-start": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-left` — a length, and only as one of this project's tokens. */
  "scroll-margin-left": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-right` — a length, and only as one of this project's tokens. */
  "scroll-margin-right": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-margin-top` — a length, and only as one of this project's tokens. */
  "scroll-margin-top": Narrowed<never, Token<"length"> | 0 | "0">;
  /** `scroll-padding` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-block` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-block": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-block-end` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-block-end": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-block-start` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-block-start": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-bottom` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-bottom": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-inline` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-inline": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-inline-end` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-inline-end": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-inline-start` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-inline-start": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-left` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-left": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-right` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-right": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scroll-padding-top` — a length or a percentage, and only as one of this project's tokens. */
  "scroll-padding-top": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `scrollbar-color` — a colour, and only as one of this project's tokens. */
  "scrollbar-color": Narrowed<"auto" | "currentcolor", Token<"color">>;
  /** `shape-margin` — a length or a percentage, and only as one of this project's tokens. */
  "shape-margin": Narrowed<never, Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `stop-color` — a colour, and only as one of this project's tokens. */
  "stop-color": Narrowed<"currentcolor", Token<"color">>;
  /** `stroke-color` — a colour, and only as one of this project's tokens. */
  "stroke-color": Narrowed<"currentcolor", Token<"color">>;
  /** `stroke-miterlimit` — a number, and this project's tokens of that kind. */
  "stroke-miterlimit": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"number" | "integer">>;
  /** `text-decoration-color` — a colour, and only as one of this project's tokens. */
  "text-decoration-color": Narrowed<"currentcolor", Token<"color">>;
  /** `text-decoration-inset` — a length or a percentage, and only as one of this project's tokens. */
  "text-decoration-inset": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `text-emphasis-color` — a colour, and only as one of this project's tokens. */
  "text-emphasis-color": Narrowed<"currentcolor", Token<"color">>;
  /** `text-fit` — a percentage, and this project's tokens of that kind. */
  "text-fit": Narrowed<"consistent" | "grow" | "none" | "per-line" | "per-line-all" | "shrink", CssDimension<"%"> | Token<"percentage">>;
  /** `text-size-adjust` — a percentage, and this project's tokens of that kind. */
  "text-size-adjust": Narrowed<"auto" | "none", CssDimension<"%"> | Token<"percentage">>;
  /** `timeline-trigger-activation-range` — a length or a percentage, and only as one of this project's tokens. */
  "timeline-trigger-activation-range": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `timeline-trigger-activation-range-end` — a length or a percentage, and only as one of this project's tokens. */
  "timeline-trigger-activation-range-end": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `timeline-trigger-activation-range-start` — a length or a percentage, and only as one of this project's tokens. */
  "timeline-trigger-activation-range-start": Narrowed<"contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `timeline-trigger-active-range` — a length or a percentage, and only as one of this project's tokens. */
  "timeline-trigger-active-range": Narrowed<"auto" | "contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `timeline-trigger-active-range-end` — a length or a percentage, and only as one of this project's tokens. */
  "timeline-trigger-active-range-end": Narrowed<"auto" | "contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `timeline-trigger-active-range-start` — a length or a percentage, and only as one of this project's tokens. */
  "timeline-trigger-active-range-start": Narrowed<"auto" | "contain" | "cover" | "entry" | "entry-crossing" | "exit" | "exit-crossing" | "normal", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `top` — a length or a percentage, and only as one of this project's tokens. */
  "top": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `transition-delay` — a time, and this project's tokens of that kind. */
  "transition-delay": Narrowed<never, CssDimension<CssTimeUnit> | Token<"time">>;
  /** `transition-duration` — a time, and this project's tokens of that kind. */
  "transition-duration": Narrowed<never, CssDimension<CssTimeUnit> | Token<"time">>;
  /** `view-timeline-inset` — a length or a percentage, and only as one of this project's tokens. */
  "view-timeline-inset": Narrowed<"auto", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `widows` — a whole number, and this project's tokens of that kind. */
  "widows": Narrowed<never, number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
  /** `width` — a length or a percentage, and only as one of this project's tokens. */
  "width": Narrowed<"auto" | "fit-content" | "max-content" | "min-content", Token<"length" | "length-percentage" | "percentage"> | 0 | "0">;
  /** `word-spacing` — a length, and only as one of this project's tokens. */
  "word-spacing": Narrowed<"normal", Token<"length"> | 0 | "0">;
  /** `z-index` — a whole number, and this project's tokens of that kind. */
  "z-index": Narrowed<"auto", number | `${number}` | `${string}(${string})` | Token<"integer" | "number">>;
}

/** What this project's blocks are checked against — the shipped map, with those replaced. */
export type CssProperties = Omit<Base, keyof Narrowings> & Narrowings;

/** The shape of one block here. The virtual file reads this. */
export type CssBlockShape = Partial<CssProperties> & {
  [nested: `&${string}`]: CssBlockShape[];
} & { [at: `@${string}`]: CssBlockShape[] } & { [dashed: `-${string}`]: CssValue };
export type {
  CssBlock,
  CssCondition,
  CssFontFaceDescriptors,
  CssGlobal,
  CssKeyframesShape,
  CssPropertyDescriptors,
  CssRegistered,
  CssSpreadable,
  CssValue,
  CssVar,
  Keyword,
  Narrowed,
  StyleValue,
};

/**
 * What one property accepts in this project, as an ELEMENT takes it — `const gap: Value<"gap"> = "8px"`.
 *
 * A value made outside a block goes onto an element, a `style` or a registered property, and
 * every value there is a string — so a number the block's shape holds is written as text.
 */
export type Value<P extends keyof CssProperties> = Spelled<CssProperties[P]>;
type Spelled<V> = V extends number ? `${V}` : V;

/** Every `color` token this project declares. */
export type ColorToken = typeof $color.page | typeof $color.text | typeof $color.muted | typeof $color.accent | typeof $color.onAccent | typeof $color.surface | typeof $color.line | typeof $color.code;

/** Every `length` token this project declares. */
export type LengthToken = typeof $space.xs | typeof $space.s | typeof $space.m | typeof $space.l | typeof $space.xl | typeof $size.line | typeof $size.focus | typeof $size.card | typeof $size.column | typeof $size.screen | typeof $radius.s | typeof $radius.m | typeof $radius.l | typeof $font.s | typeof $font.l;

/** Every token this project declares, by kind — what `AnyToken` reads. */
export interface TokenByKind {
  "color": ColorToken;
  "length": LengthToken;
}

/** Any token of a kind — `const tone: AnyToken<"color"> = toggle ? $a.b : $a.c`. */
export type AnyToken<K extends keyof TokenByKind> = TokenByKind[K];
