// Generated by scripts/build-css-properties.mjs from mdn-data. Do not edit.
//
// Types only, and no runtime: this is what `@ramonda/css` re-exports, and that entry imports
// nothing. 63 units, 5 families with more than one.

/** Every unit CSS has, from `mdn-data` — the same list `unknown-unit` measures a typo against. */
export type CssUnit = "%" | "cap" | "ch" | "cm" | "cqb" | "cqh" | "cqi" | "cqmax" | "cqmin" | "cqw" | "deg" | "dpcm" | "dpi" | "dppx" | "dvb" | "dvh" | "dvi" | "dvmax" | "dvmin" | "dvw" | "em" | "ex" | "fr" | "grad" | "hz" | "ic" | "in" | "khz" | "lh" | "lvb" | "lvh" | "lvi" | "lvmax" | "lvmin" | "lvw" | "mm" | "ms" | "pc" | "pt" | "px" | "q" | "rad" | "rcap" | "rch" | "rem" | "rex" | "ric" | "rlh" | "s" | "svb" | "svh" | "svi" | "svmax" | "svmin" | "svw" | "turn" | "vb" | "vh" | "vi" | "vmax" | "vmin" | "vw" | "x";

/** The 49 `<length>` units. `CssDimension<CssLengthUnit>` is a length and nothing else. */
export type CssLengthUnit = "cap" | "ch" | "cm" | "cqb" | "cqh" | "cqi" | "cqmax" | "cqmin" | "cqw" | "dvb" | "dvh" | "dvi" | "dvmax" | "dvmin" | "dvw" | "em" | "ex" | "ic" | "in" | "lh" | "lvb" | "lvh" | "lvi" | "lvmax" | "lvmin" | "lvw" | "mm" | "pc" | "pt" | "px" | "q" | "rcap" | "rch" | "rem" | "rex" | "ric" | "rlh" | "svb" | "svh" | "svi" | "svmax" | "svmin" | "svw" | "vb" | "vh" | "vi" | "vmax" | "vmin" | "vw";

/** The 4 `<angle>` units. `CssDimension<CssAngleUnit>` is an angle and nothing else. */
export type CssAngleUnit = "deg" | "grad" | "rad" | "turn";

/** The 2 `<time>` units. `CssDimension<CssTimeUnit>` is a time and nothing else. */
export type CssTimeUnit = "ms" | "s";

/** The 4 `<resolution>` units. `CssDimension<CssResolutionUnit>` is a resolution and nothing else. */
export type CssResolutionUnit = "dpcm" | "dpi" | "dppx" | "x";

/** The 2 `<frequency>` units. `CssDimension<CssFrequencyUnit>` is a frequency and nothing else. */
export type CssFrequencyUnit = "hz" | "khz";

/**
 * A number with a unit on it, for the declaration that MAKES one rather than for the block.
 *
 * ```ts
 * const border: CssDimension = `${this.weight}px`;      // fine
 * const border: CssDimension = `${this.weight}pddx`;    // TS2322, on this line
 * const gap: CssDimension<"px"> = `${this.gap}rem`;     // TS2322 — this app has settled on px
 * ```
 *
 * No `as const` is needed: the annotation is the context. It works in a getter, which is where a
 * value like this is usually made.
 *
 * **What it deliberately admits.** Any call — `calc()`, `min()`, `clamp()`, `var()` — because each
 * can produce any dimension and nothing in a type can read inside one. So `calc(1rem + 2px)` passes
 * `CssDimension<"px">`, and so would `foo(1)`. Refusing calls would make the type useless in the
 * one place authors reach for it.
 */
export type CssDimension<Unit extends CssUnit = CssUnit> = `${number}${Unit}` | 0 | "0" | `${string}(${string})`;
