/**
 * Stages the language-service plugin inside the extension, so both of an editor's TypeScript
 * servers can load it.
 *
 *     node tools/vscode-css/build-plugin.mjs            writes it
 *     node tools/vscode-css/build-plugin.mjs --check    fails instead, for CI
 *
 * ## Why the extension carries a plugin at all
 *
 * An editor runs two TypeScript servers. The syntax one never opens a `tsconfig.json`, which is
 * where a project names this plugin — so it reads a style block as plain TypeScript and formats,
 * folds and outlines it wrongly. That is what `useSyntaxServer: "never"` exists to avoid.
 *
 * `contributes.typescriptServerPlugins` is the other door: VS Code passes it as `--globalPlugins` to
 * **both** servers. Measured through a real `tsserver` on a file holding a block, asking the syntax
 * server to format it: 20 edits without the plugin, 0 with it — the same answer the semantic server
 * gives. So the setting stops being necessary.
 *
 * ## Why the name must be `@ramonda/css/plugin` exactly, and why a SHIM is staged
 *
 * `enableGlobalPlugins` skips a global name the project's `tsconfig.json` already lists, so sharing
 * the name is what stops the plugin loading twice in the semantic server.
 *
 * But sharing it is not enough on its own. Contributing a plugin puts this directory FIRST in
 * `tsserver`'s candidate paths, and a plugin named in a `tsconfig.json` is resolved from that same
 * list — so the copy staged here would take over checking for every project, replacing whatever
 * `@ramonda/css` that project installed. Measured on one project, before and after the
 * contribution:
 *
 *     without   Loading @ramonda/css/plugin from …/node_modules/typescript/lib/typescript.js/../../..
 *     with      Loading @ramonda/css/plugin from …/tools/vscode-css
 *
 * So what is staged under that name is `plugin-shim.cjs`, which hands over to the project's own
 * plugin when it has one and runs this copy only when it does not — which is every project the
 * syntax server opens.
 *
 * ## Where it goes, and why there
 *
 * `tsserver` resolves a plugin by joining the probe location with `node_modules` and requiring the
 * name from there — `combinePaths(initialDir, "node_modules")`, read out of `typescript.js`. VS Code
 * passes the extension's own directory as that probe location, so the only path that resolves is
 * `<extension>/node_modules/@ramonda/css`. It is a build artefact: `node_modules` is ignored by git,
 * and `.vscodeignore` un-ignores this one subtree so it reaches the `.vsix`.
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..");
const css = join(root, "packages", "css");

const check = process.argv.includes("--check");

const built = join(css, "dist", "plugin.cjs");
if (!existsSync(built)) {
  console.error(`\n[extension] ${built} is not there.`);
  console.error(`[extension] run \`pnpm --filter @ramonda/css build\` first.\n`);
  process.exit(1);
}

const version = JSON.parse(readFileSync(join(css, "package.json"), "utf8")).version;
const staged = join(here, "node_modules", "@ramonda", "css");

/**
 * The smallest manifest that resolves — a name, the version, and the one export.
 *
 * `require` is what `tsserver` uses, so the CommonJS build is the only one that has to be here. The
 * version is carried so a `.vsix` can be traced to the package it was cut from: the syntax server
 * runs THIS copy while the semantic one runs the project's, and knowing they differ is the first
 * thing anybody debugging that pair needs.
 */
const manifest = {
  name: "@ramonda/css",
  version,
  private: true,
  description: "The language-service plugin, staged inside the Ramonda CSS extension. Generated — do not edit.",
  // Both spellings of the same file. `tsserver` resolves a plugin with TypeScript's own node10
  // resolver, which does NOT read `exports` — measured: with the entry only in `exports`, the load
  // from the extension FAILED and the log fell through to the next candidate path. So the file has
  // to sit where a bare subpath lands. `exports` is listed as well, because Node's own resolver
  // refuses a subpath a package does not declare, and `plugin-shim.cjs` is required through it.
  exports: { "./plugin": "./plugin.js" },
};

/**
 * What `tsserver` loads is the SHIM, not the plugin — see `plugin-shim.cjs` for why, and for the
 * measurement that made it necessary.
 *
 * A generated one-liner rather than a copy of the shim: the shim is a source file of this
 * extension, reviewed, formatted and linted like the rest of it, and a copy in a build artefact
 * would be a second one to keep in step.
 */
const stub =
  `// Generated by tools/vscode-css/build-plugin.mjs. The plugin the extension contributes is the\n` +
  `// shim beside it, which prefers the PROJECT's own @ramonda/css. Do not edit.\n` +
  `module.exports = require("../../../plugin-shim.cjs");\n`;

const files = [
  [join(staged, "package.json"), `${JSON.stringify(manifest, null, 2)}\n`],
  [join(staged, "plugin.js"), stub],
  [join(staged, "dist", "plugin.cjs"), readFileSync(built, "utf8")],
];

const stale = files.filter(([path, text]) => !existsSync(path) || readFileSync(path, "utf8") !== text);

if (check) {
  if (stale.length === 0) {
    console.log(`[extension] the staged plugin matches @ramonda/css@${version}`);
    process.exit(0);
  }
  console.error(`\n[extension] the plugin staged in the extension is not the one this package builds:\n`);
  for (const [path] of stale) console.error(`  ${path.slice(root.length + 1)}`);
  console.error(`\n[extension] run \`node tools/vscode-css/build-plugin.mjs\` and commit nothing — it is ignored —`);
  console.error(`[extension] but the \`.vsix\` must be cut after it.\n`);
  process.exit(1);
}

rmSync(staged, { recursive: true, force: true });
for (const [path, text] of files) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

const size = (Buffer.byteLength(files[2][1]) / 1024).toFixed(0);
console.log(`[extension] staged @ramonda/css@${version} plugin (${size} KB) at node_modules/@ramonda/css`);
